# Generated by Django 5.1.3 on 2024-12-05 19:32

import inventario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_proveedor_alter_categoria_nombre_tipogasto_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[inventario.validators.validar_minimo_caracteres, inventario.validators.validar_maximo_caracteres]),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='description',
            field=models.TextField(max_length=200, validators=[inventario.validators.validar_minimo_caracteres, inventario.validators.validar_maximo_caracteres, inventario.validators.validar_campo_string]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=100, validators=[inventario.validators.validar_minimo_caracteres, inventario.validators.validar_maximo_caracteres]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=100, validators=[inventario.validators.validar_no_campo_vacio, inventario.validators.validar_minimo_caracteres]),
        ),
        migrations.AlterField(
            model_name='tipogasto',
            name='nombre_tipo_gasto',
            field=models.CharField(max_length=100, validators=[inventario.validators.validar_no_campo_vacio, inventario.validators.validar_minimo_caracteres]),
        ),
    ]
